# Generated by Django 4.0.3 on 2022-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_ratings_api', '0003_song_field_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='field_duration',
            new_name='song_duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
    ]
