# Generated by Django 4.0.3 on 2022-04-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_ratings_api', '0004_rename_field_duration_song_song_duration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_duration',
            new_name='duration',
        ),
    ]
