# Generated by Django 4.0.3 on 2022-04-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_ratings_api', '0005_rename_song_duration_song_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumreview',
            old_name='content',
            new_name='comment',
        ),
    ]
