# Generated by Django 4.0.3 on 2022-04-19 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_ratings_api', '0006_rename_content_albumreview_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumreview',
            old_name='comment',
            new_name='review_text',
        ),
        migrations.RenameField(
            model_name='albumreviewcomment',
            old_name='content',
            new_name='comment_text',
        ),
    ]
